#!/usr/bin/env bash

# brew-commons

brew update
brew upgrade

brew tap homebrew/science
brew tap homebrew/dupes

brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
brew install findutils  
brew install homebrew/dupes/grep

brew install zsh
brew install python
brew install git
brew install ack
brew install tree
brew install tmux
brew install ctags
brew install cmake
brew install wget
brew install vim
brew install macvim
brew install z

brew cleanup
