#!/usr/bin/env bash

# install

for file in {codestyles,colors,templates}; do
    TARGET="$(cd $(dirname $0) ; pwd -P)/$file"
    LINK="$HOME/Library/Preferences/AndroidStudioPreview/$file"
    if [[ -h $LINK ]]; then
        echo "[OK] Relinkng $LINK to $TARGET"
        ln -sf $TARGET "$HOME/Library/Preferences/AndroidStudioPreview"
    elif [[ ! -e $LINK ]]; then
        echo "[OK] Linking $LINK to $TARGET"
        ln -s $TARGET $LINK
    else
        echo "[XX] $LINK exists as a real file, skipping"        
    fi
done
unset file TARGET LINK
