#!/usr/bin/env bash

# install

for file in {codestyles,colors,templates}; do
    TARGET="$(cd $(dirname $0) ; pwd -P)/$file"
    ALIAS="$HOME/Library/Preferences/AndroidStudioPreview/$file"
    if [[ -h $ALIAS ]]; then
        echo "[OK] Relinkng $ALIAS to $TARGET"
        ln -sf $TARGET "$HOME/Library/Preferences/AndroidStudioPreview"
    elif [[ ! -e $ALIAS ]]; then
        echo "[OK] Linking $ALIAS to $TARGET"
        ln -s $TARGET $ALIAS
    else
        echo "[XX] $ALIAS exists as a real file, skipping"        
    fi
done
unset file TARGET ALIAS
