#!/usr/bin/env bash

# install

DIR=$( cd "$( dirname "$0" )" && pwd )
for file in {.zshrc,.ackrc,.ctags,.tmux.conf,.gitignore_global,.vimrc,.vim}; do
    TARGET="$DIR/$file"
    DEST="$HOME/$file"
    if [[ -h $DEST ]]; then
        echo "Relinkng $DEST to $TARGET"
        ln -sf $TARGET $HOME
    elif [[ ! -e $DEST ]]; then
        echo "Linking $DEST to $TARGET"
        ln -s $TARGET $DEST
    else
        echo "$DEST exists as a real file, skipping"        
    fi
done
unset file DIR TARGET DEST
