#!/usr/bin/env bash

# install

DIR=$( cd "$( dirname "$0" )" && pwd )
for file in {.zshrc,.ackrc,.ctags,.tmux.conf,.gitignore_global,.vimrc,.vim}; do
    TARGET="$DIR/$file"
    DOTF="$HOME/$file"
    if [[ -h $DOTF ]]; then
        echo "Relinkng $DOTF to $TARGET"
        ln -sf $TARGET $HOME
    elif [[ ! -e $DOTF ]]; then
        echo "Linking $DOTF to $TARGET"
        ln -s $TARGET $DOTF
    else
        echo "$DOTF exists as a real file, skipping"        
    fi
done
unset file DIR TARGET DOTF
