#!/usr/bin/env bash

# install

for file in {zsh/.zshrc,zsh/.zsh,ack/.ackrc,ctags/.ctags,tmux/.tmux.conf,git/.gitconfig,git/.gitignore_global,vim/.vimrc,vim/.vim}; do
    TARGET="$(cd $(dirname $0) ; pwd -P)/$file"
    LINK=$HOME/$(basename "$file")
    if [[ -h $LINK ]]; then
        echo "[OK] Relinkng $LINK to $TARGET"
        ln -sf $TARGET $HOME
    elif [[ ! -e $LINK ]]; then
        echo "[OK] Linking $LINK to $TARGET"
        ln -s $TARGET $LINK
    else
        echo "[XX] $LINK exists as a real file, skipping"
    fi
done
unset file TARGET LINK
